version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3303:3303'  # Map your application's port to host

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'  # Map PostgreSQL port to host

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'  # Map Swagger UI port to host
    environment:
      API_URL: http://backend:3303/docs-json  # Replace with your Swagger JSON endpoint

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: youremail@example.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
    ports:
      - '5050:80'  # Map PgAdmin port to host