name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v5

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=my-docker-image-${GITHUB_SHA::8}
          docker build -t $IMAGE_NAME -f /deployment/Dockerfile .
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
          docker tag $IMAGE_NAME registry.heroku.com/HEROKU_BACKEND_APP_NAME/web
          docker push registry.heroku.com/HEROKU_BACKEND_APP_NAME/web
          echo "DOCKER_IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Deploy to Heroku
        run: |
          wget https://toolbelt.heroku.com/download/ubuntu -O heroku.tar.gz
          tar -xvzf heroku.tar.gz
          ./heroku container:release -a HEROKU_BACKEND_APP_NAME web

      - name: Clean up
        run: |
          docker buildx prune -f